### ISSUE TITLE
fails with "Symbol's value as variable is void: info-mode-map"

### ISSUE THREAD

**Issue by dasoju** [kickingvegas/casual-suite#13]
Hi 
after install the package and added
define-key info-mode-map (kbd "C-o") **#'casual-info-tmenu)**
i get following error
Symbol's value as variable is void: info-mode-map

i added (require 'info) but still fails
finally i had to comment out the above line to avoid the error at startup

**Comment by kickingvegas** [comment]
Thanks for submitting this. I won't be able to investigate until Friday but in the interim please ensure that all packages have been updated. Also, does info work for you? That message on info-mode-map makes me suspect that somehow Casual Info is being loaded before the load-path for Info is available.

**Comment by kickingvegas** [comment]
Figured it out. Documentation bug in Casual Suite. Please use the following install statement. 

```
(keymap-set Info-mode-map "C-o" #'casual-info-tmenu)
```

Note the capitalization on `Info-mode-map`.

**Comment by kickingvegas** [comment]
@dasoju Documentation fix forthcoming in a new release of Casual Suite. That said, the above fix should work for you as there are no code changes to Casual Suite.

**Comment by dasoju** [comment]
Thanks for the prompt fix Charles, yes it works now !!
