### ISSUE TITLE
init fails with latest update 

### ISSUE THREAD

**Issue by dasoju** [kickingvegas/casual-suite#23]
hi
emacs init fails with the following error
Symbol's function definition is void: static-if

I commented out 
;; (require 'casual-suite) 

and init passes, hence concluding it is due to the latest update

**Comment by kickingvegas** [comment]
Thanks for raising this. That said, not clear on how to reproduce. Please share your init code and the full error message.

**Comment by dasoju** [comment]
i see its erroring out due to following in the transient package, below is the snapshot.
Not sure where static-if is defined, I am using emacs 29.1 (mitsuharu version)  
transient.el:(static-if (>= emacs-major-version 30) ;transient--wrap-command

<img width="1688" alt="image" src="https://github.com/user-attachments/assets/a695e9fc-ceaf-4063-a957-50a4472495b4">

**Comment by dasoju** [comment]
it started breaking after updating to new transient release 
transient-20240713.2102

I will file a bug on transient too

**Comment by kickingvegas** [comment]
@dasoju Unfortunately I'm not seeing issues with Transient 20240713.2102 as it is what is installed on my system. Noticed that you are using Emacs 29.1 from mitsuharu. If you are using MacPorts, I highly recommend using the emacs-mac-app-devel package as it will have the latest 29.4 version. This is the build of Emacs that I use.

https://ports.macports.org/port/emacs-mac-app-devel/

**Comment by kickingvegas** [comment]
Also just re-verified casual-suite install on Emacs 29.4 running on Ubuntu Linux. No issues found.

**Comment by dasoju** [comment]
Sorry for the trouble
looks like issue with transient installation, some of the dependent packages were deleted

reinstalling transient resolved the issue 

Thanks !!

**Comment by kickingvegas** [comment]
@dasoju all good! Closing.
