### ISSUE TITLE
Replace porcelain with user interface

### ISSUE THREAD

**Issue by kickingvegas** [kickingvegas/casual-suite#31]
Replace term porcelain with user interface

**Comment by phil-s** [comment]
I came here to make the exact same suggestion.

"Porcelain" and "Plumbing" for software commands is terminology I've personally only ever seen used with Git, to differentiate the different types of command that it provides.

I think *many* people will have no idea what "porcelain" is supposed to mean (and I'd argue that the intended analogy isn't even apparent when it's not being paired with "plumbing"), whereas pretty much *everyone* understands "user interface" or just "UI".
